#!/usr/bin/env node
/**
 * install: npm -g install bitcoinjs-lib
 * run: node p2pkh-electrum.js YourAddress 2>/dev/null | jq
 * note: i am not a dev.
**/

var bitcoin = require('bitcoinjs-lib'), 
address = process.argv.slice(2)[0].toString(),
scriptPubKey;

let decode = bitcoin.address.fromBase58Check(address);

// P2PKH
if (decode.version === 60)
    scriptPubKey = bitcoin.payments.p2pkh({ hash: decode.hash }).output;
// P2SH
else if (decode.version === 85)
    scriptPubKey = bitcoin.payments.p2sh({ hash: decode.hash }).output;
else{
    console.log("error, unknown version: " + decode.version);
}
    

let scriptPubKey_hash = bitcoin.crypto.sha256(scriptPubKey);
let scriptPubKey_hash_reverse = Buffer.from(scriptPubKey_hash.reverse());
console.log(scriptPubKey_hash_reverse.toString('hex'));

// EOF
